# Generated by Django 3.2.21 on 2023-11-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
